DESC        = Chapter 34 -- adding a system call, end to end (4 files)
OVERLAY     = test.c:user/programs/test.c
PATCHES     = patch.py
SCREEN_ARGS = --wait 10 --type "run /bin/user_test\n" --settle 4

include ../common/common.mk
