DESC        = Chapter 35 -- a user program using the whole libc
OVERLAY     = test.c:user/programs/test.c
SCREEN_ARGS = --wait 10 --type "run /bin/user_test\n" --settle 5

include ../common/common.mk
