DESC        = Chapter 24 -- reading a line, and the NUL-termination trap
OVERLAY     = test.c:user/programs/test.c
SCREEN_ARGS = --wait 10 --type "run /bin/user_test\nhello there\n" --settle 4

include ../common/common.mk
