StylesPath = styles
MinAlertLevel = warning
Vocab = OS

Packages = Google, write-good, proselint

[*.md]
BasedOnStyles = Vale, Google, write-good, proselint

# Google — disable rules that don't fit this book
Google.FirstPerson = NO
Google.We = NO
Google.Will = NO
Google.Contractions = NO
Google.Acronyms = NO
Google.Parens = NO
Google.Semicolons = NO
Google.Headings = NO
Google.Colons = NO
Google.WordListCase = NO
Google.Exclamation = NO
Google.Units = NO
